sudo: false

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "14"

matrix:
  include:
    - os: linux
      # reports combined coverage report to coveralls (Node older, stable, latest)
      script: npm run travis
    - os: osx
      script: npm run tests
    - os: win
      script: npm run tests
